// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCQQKSDCagcop-iyxfI75H7MTgkFtRQfY',
    appId: '1:472616071636:web:dd3c29ea93779b11a22641',
    messagingSenderId: '472616071636',
    projectId: 'flutter-carrot',
    authDomain: 'flutter-carrot.firebaseapp.com',
    databaseURL: 'https://flutter-carrot-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-carrot.appspot.com',
    measurementId: 'G-DC2MDQ8ZGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3FAIQy84henS6jVi52r-wdKS6eaZwzvc',
    appId: '1:472616071636:android:ae9497058c65ce6ea22641',
    messagingSenderId: '472616071636',
    projectId: 'flutter-carrot',
    databaseURL: 'https://flutter-carrot-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-carrot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeRI8zPazNPH3zEimpIpaFL7yFZ_kd_A4',
    appId: '1:472616071636:ios:1e34764f35d96413a22641',
    messagingSenderId: '472616071636',
    projectId: 'flutter-carrot',
    databaseURL: 'https://flutter-carrot-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-carrot.appspot.com',
    iosBundleId: 'com.example.carrotClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeRI8zPazNPH3zEimpIpaFL7yFZ_kd_A4',
    appId: '1:472616071636:ios:1e34764f35d96413a22641',
    messagingSenderId: '472616071636',
    projectId: 'flutter-carrot',
    databaseURL: 'https://flutter-carrot-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-carrot.appspot.com',
    iosBundleId: 'com.example.carrotClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCQQKSDCagcop-iyxfI75H7MTgkFtRQfY',
    appId: '1:472616071636:web:9561e3a12f32822da22641',
    messagingSenderId: '472616071636',
    projectId: 'flutter-carrot',
    authDomain: 'flutter-carrot.firebaseapp.com',
    databaseURL: 'https://flutter-carrot-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-carrot.appspot.com',
    measurementId: 'G-SQ84GRDF8S',
  );
}
